apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gs-springboot-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: gs-springboot.k3s1.idealo.devel
  - http:
      paths:
      - path: /
        backend:
          serviceName: gs-springboot
          servicePort: 80
