apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    argocd.argoproj.io/instance: gs-springboot
  name: gs-springboot-ingress
spec:
  rules:
  - host: gs-springboot-dev.eu.idealo.com
    http:
      paths:
      - backend:
          serviceName: gs-springboot
          servicePort: 80
